name: Deploy Static Website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BUCKET_NAME:           my-static-site-bucket-0355   # keep in sync with variables.tf file

    steps:
    # 1️⃣  Check out repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣  Install Terraform CLI
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.7.5   # or omit to install latest GA

    # 3️⃣  Terraform init
    - name: Terraform Init
      run: terraform init

    # 4️⃣  Terraform apply (creates the S3 bucket + policy)
    - name: Terraform Apply
      run: terraform apply -auto-approve

    # 5️⃣  (Optional) wait a few seconds for S3 consistency
    - name: Wait for bucket to be ready
      run: sleep 10

    # 6️⃣  Upload website files to S3
    - name: Upload static files
      run: |
        aws s3 cp index.html  s3://$BUCKET_NAME/ --acl public-read
        aws s3 cp styles.css s3://$BUCKET_NAME/ --acl public-read
        aws s3 cp script.js  s3://$BUCKET_NAME/ --acl public-read
  
