name: Deploy Static Website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BUCKET_NAME: my-static-site-bucket-js

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install AWS CLI (official installer)
      run: |
       curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
       unzip awscliv2.zip
       sudo ./aws/install --update

    - name: Terraform Init & Apply
      run: |
        terraform init
        terraform apply -auto-approve

    - name: Upload Website Files to S3
      run: |
        aws s3 cp index.html s3://$BUCKET_NAME/ --acl public-read
        aws s3 cp styles.css s3://$BUCKET_NAME/ --acl public-read
        aws s3 cp script.js s3://$BUCKET_NAME/ --acl public-read    
